// ─────────────────────────────────────────────────────────────────────────
//  Smoquit — the sender.
//
//  Runs on a schedule in Supabase and asks, for every phone that has said
//  yes: is there anything worth interrupting this person for right now? It
//  answers with dueAlerts() — the SAME function the app itself uses, bundled
//  in from app/src/domain/alerts.js, not a second copy of the rules. That is
//  the whole design. A reimplementation here would drift within a month,
//  and the two would disagree about somebody's streak in a notification
//  they cannot check against the app they are not looking at.
//
//  DO NOT EDIT THE BUILT FILE. This is the source; supabase-send-alerts.js
//  at the repository root is what gets pasted into the dashboard, and it is
//  generated by scripts/build-edge.mjs. scripts/check-edge.mjs fails the
//  build if the two have drifted, for the same reason the build refuses to
//  leave index.html stale.
//
//  Three things this is careful about, all learned from the shape of the
//  data rather than from taste:
//
//    THE TIMEZONE. Every day in this app is a local day and this process is
//    in UTC. domain/zone.js does the shift; the comment there is the
//    explanation and it is worth reading before changing anything here.
//
//    SAYING IT TWICE. The `alerts` row records what has already been said,
//    and it is shared with the app. Writing the seen mark back is what stops
//    a person being told about their streak here and again in a banner ten
//    minutes later. The merge rule — earliest sighting wins — was written in
//    the browser for exactly this.
//
//    ONE BAD ROW. A person with a corrupt log, a dead endpoint or a
//    timezone Intl has never heard of must not take down the batch. Every
//    subscriber is wrapped, and a failure is counted rather than thrown.
// ─────────────────────────────────────────────────────────────────────────

import { createClient } from "npm:@supabase/supabase-js@2";
import webpush from "npm:web-push@3.6.7";

import { dueAlerts, markSeen, pickAlert } from "../src/domain/alerts.js";
import { pushPayload } from "../src/domain/notify.js";
import { buildProfile } from "../src/domain/profile.js";
import { inZone } from "../src/domain/zone.js";
import { SQ_HE } from "../src/i18n/he.js";
import { translate } from "../src/i18n/translate.js";

/** How many endpoints may reject us before we stop paying to try. */
const MAX_FAILURES = 5;

/** Rows the sender needs for one person. */
const KEYS = ["logs", "cravings", "goal", "settings", "meta", "alerts"];

/**
 * Naming an hour, for a reader whose language we were told rather than are
 * in. The twin of i18n/format.js — deliberately not imported from there,
 * because that file reads the ambient SQ_LANG and there is no such thing
 * here; every account in the batch may want a different answer.
 */
const hourIn = (lang) => (hour) =>
  lang === "he"
    ? `${String(hour).padStart(2, "0")}:00`
    : `${hour === 0 ? 12 : hour > 12 ? hour - 12 : hour}${hour >= 12 ? "pm" : "am"}`;

/** Everything stored for one user, as the app would see it. */
async function rowsFor(db, userId) {
  const { data, error } = await db
    .from("user_data")
    .select("key, value")
    .eq("user_id", userId)
    .in("key", KEYS);
  if (error) throw error;

  const rows = {};
  for (const row of data ?? []) rows[row.key] = row.value;
  return rows;
}

/**
 * Decide, for one subscription, and send if there is anything to send.
 *
 * @returns {"sent"|"quiet"|"gone"} what happened, for the run's summary
 */
async function handle(db, subscription, now) {
  const rows = await rowsFor(db, subscription.user_id);
  const settings = rows.settings ?? {};
  const lang = settings.lang === "he" ? "he" : "en";

  // Into the reader's clock, once, before anything reads an hour.
  const local = inZone({
    tz: subscription.tz,
    logs: rows.logs ?? {},
    cravings: rows.cravings ?? {},
    now,
  });

  const profile = buildProfile({
    logs: local.logs,
    cravings: local.cravings,
    goal: rows.goal,
    settings,
    meta: rows.meta,
    now: local.now,
  });

  const alert = pickAlert(
    dueAlerts({
      profile,
      logs: local.logs,
      cravings: local.cravings,
      goal: rows.goal,
      settings,
      seen: rows.alerts?.seen,
      now: local.now,
    }),
  );
  if (!alert) return "quiet";

  const t = (key, params) => translate(lang === "he" ? SQ_HE : null, key, params);
  const payload = pushPayload(alert, { t, hour: hourIn(lang) });

  try {
    await webpush.sendNotification(
      {
        endpoint: subscription.endpoint,
        keys: { p256dh: subscription.p256dh, auth: subscription.auth },
      },
      JSON.stringify(payload),
    );
  } catch (err) {
    // 404 and 410 are the push service telling us this endpoint is dead —
    // the app was uninstalled, or the browser rotated it. That is not an
    // error to retry, it is a row to remove.
    const status = err?.statusCode ?? 0;
    if (status === 404 || status === 410) return "gone";
    throw err;
  }

  // Written back BEFORE we call it a success, because saying a thing twice
  // is worse than not saying it: the banner in the app reads this same row.
  const next = markSeen(rows.alerts, alert, now);
  if (next !== rows.alerts) {
    await db
      .from("user_data")
      .upsert(
        {
          user_id: subscription.user_id,
          key: "alerts",
          value: next,
          updated_at: new Date(now).toISOString(),
        },
        { onConflict: "user_id,key" },
      );
  }
  return "sent";
}

Deno.serve(async (req) => {
  // The cron calls this with the service key. Nothing else may.
  const secret = Deno.env.get("SEND_ALERTS_SECRET") ?? "";
  if (secret && req.headers.get("x-smoquit-secret") !== secret) {
    return new Response("no", { status: 401 });
  }

  webpush.setVapidDetails(
    Deno.env.get("VAPID_SUBJECT") ?? "mailto:hello@smoquit.app",
    Deno.env.get("VAPID_PUBLIC_KEY") ?? "",
    Deno.env.get("VAPID_PRIVATE_KEY") ?? "",
  );

  const db = createClient(
    Deno.env.get("SUPABASE_URL"),
    // The service role, which is the only way to read across accounts —
    // and the reason push_subscriptions grants the browser no select at all.
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
    { auth: { persistSession: false } },
  );

  const now = Date.now();
  const tally = { sent: 0, quiet: 0, gone: 0, failed: 0 };

  const { data: subscriptions, error } = await db
    .from("push_subscriptions")
    .select("user_id, endpoint, p256dh, auth, tz, failures")
    .lt("failures", MAX_FAILURES);
  if (error) return new Response(JSON.stringify({ error: error.message }), { status: 500 });

  for (const subscription of subscriptions ?? []) {
    try {
      const outcome = await handle(db, subscription, now);
      tally[outcome] += 1;
      if (outcome === "gone") {
        await db
          .from("push_subscriptions")
          .delete()
          .eq("user_id", subscription.user_id)
          .eq("endpoint", subscription.endpoint);
      }
    } catch (err) {
      // One person's bad row is not everybody's problem. Counted, so that a
      // subscription failing every quarter of an hour forever eventually
      // falls out of the query above rather than being retried until the
      // heat death of the universe.
      tally.failed += 1;
      console.error("send-alerts:", subscription.user_id, String(err?.message ?? err));
      await db
        .from("push_subscriptions")
        .update({ failures: (subscription.failures ?? 0) + 1 })
        .eq("user_id", subscription.user_id)
        .eq("endpoint", subscription.endpoint);
    }
  }

  return new Response(JSON.stringify(tally), {
    headers: { "content-type": "application/json" },
  });
});
