// The files that live beside the build output and are never generated by
// it: edited by hand, deployed as-is, no rebuild needed. Losing one takes
// the live site down, so the build fingerprints them before and after.
import { join } from "node:path";
import { tmpdir } from "node:os";

export const PROTECTED = [
  "config.js",
  "version.js",
  "storage-health.js",
  "_headers",
  "_redirects",
  "supabase-schema.sql",
  "UPLOAD-ME-README.txt",
];

export const FINGERPRINT_FILE = join(tmpdir(), "smoquit-protected-before.json");
